secret: c1-keycloak-cert
namespace: c1-ns
customer-name: customer1
redirectUriHttp: "http://customer1.com:30563/*"
redirectUriHttps: "https://customer1.com:30391/*"
clientID: "oauth2-proxy-c1"
clientSecret: "lsuaCKsXRCQ0gID8BZHYK8tfAMlxP1cR"
cookieSecret: "UmRaMTlQajM1a2ordWFYRnlJb2tjWEd2MVpCK2grOFM="
oidcIssuerUrl: "http://192.168.121.187:32598/realms/customer1"
redeemUrl: http://192.168.121.187:32598/realms/customer1/protocol/openid-connect/token
whitelistDomains: .customer1.com:*
domainName: customer1.com
redirectUrl: "https://customer1.com:30391/oauth2/callback"
caCommonName: customer1-ca
appName: app1
appDomainName: app1.customer1.com
destinationHost: httpbin.bar.cluster2
