
---
# Send traffic through oauth2-proxy
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: ext-authz-oauth2-proxy
  namespace: {{ (datasource "data").namespace }}
spec:
  selector:
    matchLabels:
      istio: ingressgateway-{{ (datasource "data").customerName }}
  action: CUSTOM
  provider:
    name: oauth2-proxy-{{ (datasource "data").namespace }}
  rules:
  - to:
    - operation:
        notPaths: ["/realms/*"]


---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: redirect-gateway
  namespace: {{ (datasource "data").namespace }}
spec:
  selector:
    istio: ingressgateway-{{ (datasource "data").customerName }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ strings.Quote (datasource "data").domainName }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ (datasource "data").customerName }}
    hosts:
    - {{ strings.Quote (datasource "data").domainName }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ (datasource "data").namespace }}
  name: redirect-vs
spec:
  hosts:
  - {{ strings.Quote (datasource "data").domainName }}
  gateways:
  - redirect-gateway
  http:
  - match:
    - uri:
        prefix: /oauth2/callback
    route:
    - destination:
        host: oauth2-proxy.{{ (datasource "data").namespace }}.svc.cluster.local
        port:
          number: 80
