apiVersion: v1
kind: Namespace
metadata:
  name: {{ (datasource "data").namespace }}
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c1-selfsigned-ca
  namespace: {{ (datasource "data").namespace }}
spec:
  isCA: true
  commonName: {{ (datasource "data").caCommonName }}
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: {{ (datasource "data").namespace }}
spec:
  ca:
    secretName: root-secret

