config:
  clientID: {{ (datasource "data").clientID }}
  clientSecret: {{ (datasource "data").clientSecret }}
  cookieSecure: false
  cookie-httponly: false
  cookieName: "my-cookie"
  cookieSecret: {{ (datasource "data").cookieSecret }}
  configFile: |-
    provider = "oidc"
    oidc_issuer_url={{ strings.Quote (datasource "data").oidcIssuerUrl }}
    scope="openid email profile"
    pass_host_header = true
    reverse_proxy = true
    auth_logging = true
    cookie_httponly = false
    cookie_refresh = "4m"
    cookie_secure = false
    email_domains = "*"
    pass_access_token = true
    pass_authorization_header = true
    request_logging = true
    #session_store_type = "redis"
    set_authorization_header = true
    set_xauthrequest = true
    silence_ping_logging = true
    skip_provider_button = true
    skip_auth_strip_headers = false
    skip_jwt_bearer_tokens = true
    ssl_insecure_skip_verify = true
    insecure_oidc_allow_unverified_email="true"
    insecure_oidc_skip_nonce = "true"
    standard_logging = true
    redirect_url={{ strings.Quote (datasource "data").redirectUrl }}
    redeem_url={{ strings.Quote (datasource "data").redeemUrl }}
    upstreams = [ "static://200" ]
    whitelist_domains = [{{ strings.Quote (datasource "data").whitelistDomains }}]
    cookie_domains = [{{ strings.Quote (datasource "data").domainName }}]
