apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ (datasource "data").namespace }}
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ (datasource "data").namespace }}
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:19.0.1
        args: ["start-dev", "--import-realm"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: KEYCLOAK_IMPORT
          value: /data/import/realm.json
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
        volumeMounts:
          - name: keycloak-volume
            mountPath: /opt/keycloak/data/import
      volumes:
        - name: keycloak-volume
          configMap:
            name: keycloak-configmap

---

apiVersion: v1
data:
  realm.json: |
    {
    "realm": "demo",
    "enabled": true,
    "users": [
        {
            "username": "keycloak",
            "enabled": true,
            "credentials": [
                {
                    "type": "password",
                    "value": "test"
                }
            ],
            "realmRoles": [
                "user"
            ]
        }
    ],
    "roles": {
        "realm": [
            {
                "name": "user",
                "description": "User privileges"
            },
            {
                "name": "admin",
                "description": "Administrator privileges"
            }
        ]
    },
    "defaultRoles": [
        "user"
    ],
    "clients": [
        {
            "clientId": "app",
            "enabled": true,
            "publicClient": true,
            "redirectUris": [
                "*"
            ],
            "webOrigins": [
                "*"
            ]
        },
        {
            "clientId": "demo-mutual-tls",
            "enabled": true,
            "publicClient": false,
            "clientAuthenticatorType": "client-x509",
            "redirectUris": [
                "*"
            ],
            "webOrigins": [
                "*"
            ],
            "attributes": {
                "x509.subjectdn": "CN=demo-mutual-tls-keycloak.*"
            }
        }
    ]
    }
  
kind: ConfigMap
metadata:
  name: keycloak-configmap
  namespace: {{ (datasource "data").namespace }}
