

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-lb-customer1
  namespace: lb-ns
spec:
  selector:
    istio: ingressgateway-lb
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.customer1.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "*.customer1.com"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: lb-ns
  name: vs-lb-customer1
spec:
  hosts:
  - "*.customer1.com"
  gateways:
  - gateway-lb-customer1
  http:
  - route:
    - destination:
        host: istio-ingressgateway-c1.c1-ns.svc.cluster.local
  tls:
  - match:
    - port: 443
      sniHosts:
      - "*.customer1.com"
    route:
    - destination:
        host: istio-ingressgateway-c1.c1-ns.svc.cluster.local
        port:
          number: 443

