---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c1-selfsigned-ca
  namespace: c1-ns
spec:
  isCA: true
  commonName: customer1.com
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: c1-ca-issuer
  namespace: c1-ns
spec:
  ca:
    secretName: root-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c1-keycloak
  namespace: c1-ns
spec:
  commonName: keycloak.customer1.com
  subject:
    organizations:
      - customer1
  dnsNames:
    - keycloak.c1-ns.svc
    - keycloak.c1-ns.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: c1-ca-issuer
  secretName: c1-keycloak-cert
